import './globals.css';
import 'styles/main.scss';
import { Inter } from 'next/font/google';
import Nav from './components/nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: {
    default: 'Al Ain Academy',
    template: '%s - Al Alin Academy'
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav></Nav>
        <div className="master-container">{children}</div>
      </body>
    </html>
  );
}
