import '../globals.css';
import 'styles/main.scss';
import { useLocale } from 'next-intl';
import { notFound } from 'next/navigation';

import { NextIntlClientProvider } from 'next-intl';

export const metadata = {
  title: {
    default: 'Al Ain Academy',
    template: '%s - Al Ain Academy',
  },
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  const locale = useLocale();
  let messages;
  try {
    messages = (await import(`/messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  if (params.locale !== locale) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body dir={locale === 'en' ? 'ltr' : 'rtl'}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
